security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: bl0g@dm1n, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/admin/login$
            security: false

        secured_area:
            pattern:    ^/admin/*
            form_login:
                check_path: hasheado_blog_admin_login_check
                login_path: hasheado_blog_admin_login
                default_target_path: hasheado_blog_admin_dashboard
                target_path_parameter: _target_path
                use_referer: true
            logout:
                path: hasheado_blog_admin_logout
                target: hasheado_blog_admin_login
            remember_me:
                key:      "%secret%"
                lifetime: 2592000 # 30 days in seconds
                path:     hasheado_blog_admin_dashboard
                domain:   ~ # Defaults to the current domain from $_SERVER

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
